apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmserver
  template:
    metadata:
      labels:
        app: gmserver
    spec:
      containers:
        - name: gmserver
          image: registry.cn-chengdu.aliyuncs.com/havario/gmserver:latest
          ports:
            - containerPort: 3000
          env:
            - name: GMDB_HOST
              value: "192.168.250.250"
            - name: GMDB_DATABASE
              value: "dev_gm"
            - name: GMDB_USER
              value: "root"
            - name: GMDB_PASSWORD
              value: "a4dbb8ac-58dc-476b-9b83-c362dd21c1b1"
            - name: GMDB_PORT
              value: "3306"
            - name: REPORTDB_HOST
              value: "192.168.250.250"
            - name: REPORTDB_DATABASE
              value: "dev_report"
            - name: REPORTDB_USER
              value: "root"
            - name: REPORTDB_PASSWORD
              value: "fe219973-afbf-4f7f-804e-46af55b89af0"
            - name: REPORTDB_PORT
              value: "3306"
            - name: ACCOUNTDB_HOST
              value: "192.168.250.250"
            - name: ACCOUNTDB_DATABASE
              value: "dev_account"
            - name: ACCOUNTDB_USER
              value: "root"
            - name: ACCOUNTDB_PASSWORD
              value: "0f4e1d5b-1298-4661-9c6e-59f132e6eaa6"
            - name: ACCOUNTDB_PORT
              value: "3306"
            - name: CENTERDB_HOST
              value: "192.168.250.250"
            - name: CENTERDB_DATABASE
              value: "dev_common"
            - name: CENTERDB_USER
              value: "root"
            - name: CENTERDB_PASSWORD
              value: "bf8b2dd1-e509-43b5-8e47-f6ab146e9ab2"
            - name: CENTERDB_PORT
              value: "3306"
            - name: GMGAME_HOST
              value: "192.168.250.251"
            - name: GMGAME_PORT
              value: "6090"
            - name: OBS_ACCESS_KEY_ID
              value: "186bc618-4e80-495a-bc8e-202421284093"
            - name: OBS_SECRET_ACCESS_KEY
              value: "03863cbd-87d7-4100-bc5b-a80f43e94f89"
            - name: OBS_SERVER
              value: "4d7857e8-5ada-4373-8d28-aeaad0af2857"
            - name: OBS_BUCKET
              value: "6f48c68e-4dd8-4fd0-9c45-10338f273f2a"
            - name: OBS_NOTIC_KEY
              value: "0402de27-d290-4fbd-b763-b9aa8c5cde00"
            - name: OBS_SERVERLIST_KEY
              value: "56430b48-5e31-4c4d-b939-93e7a602ce52"
            - name: OBS_SERVERLIST_NAME
              value: "7ec1da4e-82cd-4276-a42a-4a2554eb5441"
            - name: OBS_REFRESH_ACCESSKEY
              value: "1f5e8698-4901-4ccc-949a-909b0c1a7b04"
            - name: OBS_REFRESH_SECRETKEY
              value: "5a892439-9450-4d67-99b7-e8d609e223d9"
            - name: OBS_REFRESH_PROJECTID
              value: "ed9f293a-487f-4ef9-bfec-dbc27f7ae84a"
          volumeMounts:
            - name: gmserver-config
              mountPath: /gm-server/config
            - name: gmserver-logs
              mountPath: /gm-server/logs
            - name: gmserver-upload
              mountPath: /gm-server/upload
      volumes:
        - name: gmserver-config
          hostPath:
            path: ./gmserver/config
        - name: gmserver-logs
          hostPath:
            path: ./gmserver/logs
        - name: gmserver-upload
          hostPath:
            path: ./gmserver/upload

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmweb
  template:
    metadata:
      labels:
        app: gmweb
    spec:
      containers:
        - name: gmweb
          image: registry.cn-chengdu.aliyuncs.com/havario/gmweb:latest
          ports:
            - containerPort: 80
          env:
            - name: HTML_TITLE
              value: "p8-demo"
            - name: GMSERVER_PUBLIC_IP
              value: "192.168.250.250"
            - name: GMSERVER_PUBLIC_PORT
              value: "3000"
          volumeMounts:
            - name: gmweb-config
              mountPath: /gm-web/config
            - name: gmweb-setup
              mountPath: /gm-web/src/globle/setup.js
      volumes:
        - name: gmweb-config
          hostPath:
            path: ./gmweb/config
        - name: gmweb-setup
          hostPath:
            path: ./gmweb/setup.js

---

apiVersion: v1
kind: Service
metadata:
  name: gmserver-service
spec:
  selector:
    app: gmserver
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: gmweb-service
spec:
  selector:
    app: gmweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gmweb-config
data:
  HTML_TITLE: p8-demo
  GMSERVER_PUBLIC_IP: "192.168.250.250"
  GMSERVER_PUBLIC_PORT: "3000"