services:
  gmetl:
    image: registry.cn-chengdu.aliyuncs.com/havario/gmetl
    container_name: gmetl
    restart: unless-stopped
    environment:
      REPORTDB_HOST: 192.168.250.250
      REPORTDB_PORT: 3306
      REPORTDB_USER: root
      REPORTDB_PASSWORD: 12345678
      REPORTDB_DATABASE: example_report
    volumes:
      - ./config:/gm-etl/config
      - ./data:/gm-etl/data   # 报表数据目录挂载
      - ./logs:/gm-etl/logs
    network_mode: bridge