# bi containerized build baseimage Dockerfile
# Copyright (C) 2025 honeok <honeok@duck.com>
#
# https://github.com/honeok/archive/raw/master/jds/bi/Dockerfile_baseImage
#      __     __       _____                  
#  __ / / ___/ /  ___ / ___/ ___ _  __ _  ___ 
# / // / / _  /  (_-</ (_ / / _ `/ /  ' \/ -_)
# \___/  \_,_/  /___/\___/  \_,_/ /_/_/_/\__/ 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 or later.
# See <https://www.gnu.org/licenses/>

FROM python:3.9.20-alpine3.20

WORKDIR /

COPY requirements.txt .

RUN set -ex \
    && python3 -m pip install --no-cache-dir -r requirements.txt \
    && rm -f requirements.txt