# Description: Dockerfile for building the base image for the BI containerized environment
#
# Copyright (C) 2025 honeok <honeok@duck.com>
#
#      __     __       _____                  
#  __ / / ___/ /  ___ / ___/ ___ _  __ _  ___ 
# / // / / _  /  (_-</ (_ / / _ `/ /  ' \/ -_)
# \___/  \_,_/  /___/\___/  \_,_/ /_/_/_/\__/ 
#                                             
# License Information:
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License, version 3 or later.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

FROM python:3.9.20-alpine3.20

WORKDIR /

COPY requirements.txt .

RUN set -ex \
    && python3 -m pip install --no-cache-dir -r requirements.txt \
    && rm -f requirements.txt