services:
  nginx:
    image: honeok/nginx:1.27.3-alpine3.20
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/bi.conf:/etc/nginx/conf.d/bi.conf
      - ./logs:/var/log/nginx
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=512m
    network_mode: bridge