# Description: Dockerfile for the gameapi basic environment based on Alpine
#
# Copyright (C) 2024 - 2025 honeok <honeok@duck.com>
#      __     __       _____
#  __ / / ___/ /  ___ / ___/ ___ _  __ _  ___
# / // / / _  /  (_-</ (_ / / _ `/ /  ' \/ -_)
# \___/  \_,_/  /___/\___/  \_,_/ /_/_/_/\__/
#
# References:
# https://github.com/luarocks/luarocks/wiki/Download
# https://github.com/openresty/docker-openresty/blob/master/alpine/Dockerfile
# https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine-slim/Dockerfile
#
# License Information:
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License, version 3 or later.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

ARG RESTY_IMAGE_BASE="openresty/openresty"
ARG RESTY_IMAGE_TAG="1.27.1.1-alpine"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG} AS builder

# Docker Build Arguments
ARG RESTY_J="2"

ARG RESTY_LUAROCKS_VERSION="3.9.2"
ARG RESTY_LUAROCKS_BUILD_OPTIONS="--lua-suffix=jit --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1"

RUN set -ex \
        && apk update && apk upgrade \
        && apk add --no-cache --virtual .build-deps \
            gcc \
            g++ \
            make \
            pcre-dev \
            zlib-dev \
            openssl-dev \
            curl \
            wget \
            git \
            libtool \
            automake \
        && cd /tmp/ \
        && curl -fsL -O https://luarocks.github.io/luarocks/releases/luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
        && tar zxpf luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
        && cd luarocks-${RESTY_LUAROCKS_VERSION} \
        && ./configure \
            --prefix=/usr/local/openresty/luajit \
            --with-lua=/usr/local/openresty/luajit \
            ${RESTY_LUAROCKS_BUILD_OPTIONS} \
        && make -j${RESTY_J} \
        && make -j${RESTY_J} install \
        && cd / \
        && /usr/local/openresty/luajit/bin/luarocks install ansicolors \
        && /usr/local/openresty/luajit/bin/luarocks install argparse \
        && /usr/local/openresty/luajit/bin/luarocks install date \
        && /usr/local/openresty/luajit/bin/luarocks install etlua \
        && /usr/local/openresty/luajit/bin/luarocks install lapis \
        && /usr/local/openresty/luajit/bin/luarocks install loadkit \
        && /usr/local/openresty/luajit/bin/luarocks install lpeg \
        && /usr/local/openresty/luajit/bin/luarocks install lua-cjson \
        && /usr/local/openresty/luajit/bin/luarocks install lua-resty-hmac-ffi \
        && /usr/local/openresty/luajit/bin/luarocks install lua-resty-http \
        && /usr/local/openresty/luajit/bin/luarocks install lua-resty-mlcache \
        && /usr/local/openresty/luajit/bin/luarocks install lua-resty-openssl \
        && /usr/local/openresty/luajit/bin/luarocks install lua-resty-redis \
        && /usr/local/openresty/luajit/bin/luarocks install lua-resty-requests \
        && /usr/local/openresty/luajit/bin/luarocks install luaossl \
        && /usr/local/openresty/luajit/bin/luarocks install luasocket \
        && /usr/local/openresty/luajit/bin/luarocks install luasql-mysql MYSQL_INCDIR=/usr/include/mysql \
        && /usr/local/openresty/luajit/bin/luarocks install net-url \
        && /usr/local/openresty/luajit/bin/luarocks install pgmoon \
        && rm -rf /tmp/* \
        && apk del .build-deps

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

COPY --from=builder /usr/local/openresty /usr/local/openresty

RUN set -ex \
        && apk update && apk upgrade \
        && apk add --no-cache tzdata \
        && cp -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
        && echo "Asia/Shanghai" > /etc/timezone \
        && apk del tzdata \
        && rm -rf /var/cache/apk/* \
        && mkdir -p /var/cache/nginx \
        && addgroup -g 1001 -S nginx \
        && adduser -S -D -H -u 1001 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
        && chown -R nginx:nginx /usr/local/openresty /var/run/openresty /etc/nginx/conf.d /var/cache/nginx \
        && sed -i 's/^#user  nobody;/user  nginx;/' /usr/local/openresty/nginx/conf/nginx.conf

ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin
ENV LUA_PATH=/usr/local/openresty/lualib/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;;
ENV LUA_CPATH=/usr/local/openresty/lualib/?.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so;;